apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: boce-wac-project-ambulance-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: boce-wac-project-ambulance-webapi-config
    literals:
      - database=boce-wac-project-ambulance-wl
      - collection=appointmentslist
patches:
 - path: patches/webapi.deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: boce-wac-project-ambulance-webapi