/*
 * Patients portal for appointments management API
 *
 * Patients portal for appointments management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package boce_wac_project_ambulance_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type AppointmentsListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateAppointment - Creates a new appointment
   CreateAppointment(ctx *gin.Context)

    // DeleteAppointment - Deletes an appointment
   DeleteAppointment(ctx *gin.Context)

    // GetAppointmentsList - Provides list of all appointments
   GetAppointmentsList(ctx *gin.Context)

    // UpdateAppointment - Updates an appointment
   UpdateAppointment(ctx *gin.Context)

 }

 // partial implementation of AppointmentsListAPI - all functions must be implemented in add on files
type implAppointmentsListAPI struct {

}

func newAppointmentsListAPI() AppointmentsListAPI {
  return &implAppointmentsListAPI{}
}

func (this *implAppointmentsListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/appointment-list", this.CreateAppointment)
  routerGroup.Handle( http.MethodDelete, "/appointment-list", this.DeleteAppointment)
  routerGroup.Handle( http.MethodGet, "/appointment-list", this.GetAppointmentsList)
  routerGroup.Handle( http.MethodPut, "/appointment-list", this.UpdateAppointment)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateAppointment - Creates a new appointment
// func (this *implAppointmentsListAPI) CreateAppointment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteAppointment - Deletes an appointment
// func (this *implAppointmentsListAPI) DeleteAppointment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAppointmentsList - Provides list of all appointments
// func (this *implAppointmentsListAPI) GetAppointmentsList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateAppointment - Updates an appointment
// func (this *implAppointmentsListAPI) UpdateAppointment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

