/*
 * Patients portal for appointments management API
 *
 * Patients portal for appointments management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package boce_wac_project_ambulance_wl

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newAppointmentsListAPI()
    api.addRoutes(group)
  }
  
}